jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
    - script: |
        sudo apt update 
        sudo apt install -yy gcc cmake
      displayName: "Install build toolchain"
    - script: |
        cmake --version
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF
      displayName: 'Configure'
    - script: |
        cd build
        cmake --build .
      displayName: 'Build'
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - script: |
        cmake --version
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=OFF
      displayName: 'Configure'
    - script: |
        cd build
        cmake . --build Debug
      displayName: 'Build'
  - job: MacOS
    pool:
      vmImage: 'macOS-10.13'

    steps:
    - script: |
        cmake --version
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF
      displayName: 'Configure'
    - script: |
        cd build
        cmake --build .
      displayName: 'Build'
